language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src/

after_success:
  - vendor/bin/coveralls -vvv

notifications:
  email: false
