language: php

php:
  - 7.2
  - 7.4

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src/
  - composer phpstan-setup && composer phpstan

after_success:
  - vendor/bin/coveralls -vvv

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
